# -*- coding: utf-8 -*-
"""Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uc3vXGrra-KzDNrTZuLZLh0_38hnuIka
"""

import pandas as pd


import pandas as pd
import numpy as np
import json
from fairlearn.metrics import (
    MetricFrame,
    selection_rate,
    true_positive_rate,
    false_negative_rate,
    false_positive_rate
)

class FairnessAuditor:
    def __init__(self, data_path, threshold=0.70):
        """
        Initializes the auditor, ingests the CSV, and binarizes the scores.
        """
        self.df = pd.read_csv(data_path)
        self.threshold = threshold

        # Binarize continuous scores into hard Accept/Reject decisions
        self.df['Predicted_Label'] = (self.df['Model_Predicted_Score'] >= threshold).astype(int)
        self.df['True_Label'] = (self.df['matched_score'] >= threshold).astype(int)

    def _calculate_theil_index(self, scores):
        """
        Calculates the Generalized Entropy Index (Theil Index) on continuous scores.
        T = (1/n) * sum((b_i / mean_b) * ln(b_i / mean_b))
        """
        b = np.array(scores)
        mean_b = np.mean(b)
        if mean_b == 0:
            return 0.0
        # Add a tiny epsilon to prevent log(0)
        return float(np.mean((b / mean_b) * np.log((b / mean_b) + 1e-10)))

    def evaluate_slice(self, attribute_name, priv_group, unpriv_group, priv_values):
        """
        Evaluates the core 8 metrics for a specific demographic slice.
        """
        # Filter out rows that don't belong to the explicit privileged/unprivileged groups
        # (e.g., ignoring "Unknown" ages or middle tiers if we only want strict A/B testing)
        mask = self.df[attribute_name].isin([priv_group, unpriv_group] if isinstance(priv_group, str) else priv_values + [unpriv_group])
        slice_df = self.df[mask].copy()

        # Create a clean binary mask for Fairlearn (1 = Privileged, 0 = Unprivileged)
        if isinstance(priv_group, str):
            sensitive_features = (slice_df[attribute_name] == priv_group).astype(int)
        else:
            sensitive_features = slice_df[attribute_name].isin(priv_values).astype(int)
            priv_group = " & ".join(priv_values) # Format for JSON output

        y_true = slice_df['True_Label']
        y_pred = slice_df['Predicted_Label']

        # Initialize Fairlearn MetricFrame
        metrics_dict = {
            "selection_rate": selection_rate,
            "tpr": true_positive_rate,
            "fnr": false_negative_rate,
            "fpr": false_positive_rate
        }

        mf = MetricFrame(
            metrics=metrics_dict,
            y_true=y_true,
            y_pred=y_pred,
            sensitive_features=sensitive_features
        )

        # Extract rates for Privileged (1) and Unprivileged (0)
        sr_priv = mf.by_group['selection_rate'].iloc[1] if 1 in mf.by_group.index else 0
        sr_unpriv = mf.by_group['selection_rate'].iloc[0] if 0 in mf.by_group.index else 0

        tpr_priv = mf.by_group['tpr'].iloc[1] if 1 in mf.by_group.index else 0
        tpr_unpriv = mf.by_group['tpr'].iloc[0] if 0 in mf.by_group.index else 0

        fnr_priv = mf.by_group['fnr'].iloc[1] if 1 in mf.by_group.index else 0
        fnr_unpriv = mf.by_group['fnr'].iloc[0] if 0 in mf.by_group.index else 0

        fpr_priv = mf.by_group['fpr'].iloc[1] if 1 in mf.by_group.index else 0
        fpr_unpriv = mf.by_group['fpr'].iloc[0] if 0 in mf.by_group.index else 0

        # 1. Disparate Impact (Ratio of Selection Rates)
        disparate_impact = sr_unpriv / sr_priv if sr_priv > 0 else 0.0

        # 2. Demographic Parity Difference (Absolute Diff)
        demographic_parity_diff = abs(sr_unpriv - sr_priv)

        # 3. Statistical Parity Ratio (Min / Max Selection Rate)
        stat_parity_ratio = min(sr_unpriv, sr_priv) / max(sr_unpriv, sr_priv) if max(sr_unpriv, sr_priv) > 0 else 0.0

        # 4. Equal Opportunity Difference
        equal_opp_diff = tpr_unpriv - tpr_priv

        # 5. False Negative Rate Difference
        fnr_diff = fnr_unpriv - fnr_priv

        # 6. False Positive Rate Difference
        fpr_diff = fpr_unpriv - fpr_priv

        # 7. Average Odds Difference
        avg_odds_diff = 0.5 * (fpr_diff + equal_opp_diff)

        # 8. Theil Index (Calculated on the continuous model score)
        theil_val = self._calculate_theil_index(slice_df['Model_Predicted_Score'])

        # --- Build JSON Payload ---
        metrics_payload = [
            self._format_metric("Disparate Impact", disparate_impact, 0.80, disparate_impact >= 0.80, f"Unprivileged group is selected at {disparate_impact:.0%} the rate of the privileged group."),
            self._format_metric("Demographic Parity Difference", demographic_parity_diff, 0.10, demographic_parity_diff <= 0.10, f"Absolute selection gap is {demographic_parity_diff:.0%}."),
            self._format_metric("Statistical Parity Ratio", stat_parity_ratio, 0.80, stat_parity_ratio >= 0.80, f"Ratio of lowest to highest selection rate is {stat_parity_ratio:.2f}."),
            self._format_metric("Equal Opportunity Difference", equal_opp_diff, -0.10, equal_opp_diff >= -0.10, f"Qualified {unpriv_group} candidates have a {equal_opp_diff:.0%} difference in hiring probability."),
            self._format_metric("False Negative Rate Difference", fnr_diff, 0.10, fnr_diff <= 0.10, f"{unpriv_group} candidates are incorrectly rejected {fnr_diff:.0%} more often."),
            self._format_metric("False Positive Rate Difference", fpr_diff, 0.10, fpr_diff <= 0.10, f"{unpriv_group} candidates receive the 'benefit of the doubt' {fpr_diff:.0%} more/less often."),
            self._format_metric("Average Odds Difference", avg_odds_diff, 0.10, abs(avg_odds_diff) <= 0.10, f"Average error disparity across groups is {avg_odds_diff:.0%}."),
            self._format_metric("Theil Index", theil_val, 0.20, theil_val <= 0.20, f"Inequality in prediction distribution is {theil_val:.3f}.")
        ]

        # Determine overall status (Fail if Disparate Impact or > 2 other metrics fail)
        failed_count = sum(1 for m in metrics_payload if not m['passed'])
        audit_status = "FAIL" if (disparate_impact < 0.80 or failed_count >= 3) else "PASS"

        return {
            "audit_status": audit_status,
            "evaluated_group": {
                "attribute": attribute_name,
                "privileged": priv_group,
                "unprivileged": unpriv_group
            },
            "metrics": metrics_payload
        }

    def _format_metric(self, name, value, threshold, passed, description):
        return {
            "name": name,
            "value": round(float(value), 3),
            "threshold": threshold,
            "passed": bool(passed),
            "description": description
        }

    def run_full_audit(self):
        """
        Runs the audit across all defined socio-demographic slices.
        """
        results = [
            self.evaluate_slice("gender", "Male", "Female", None),
            self.evaluate_slice("college_tier", None, "Tier 3", ["Tier 1", "Tier 2"]),
            self.evaluate_slice("region", "Metro", "Non-Metro", None)
        ]
        return results

# --- FastAPI Integration Example ---
if __name__ == "__main__":
    auditor = FairnessAuditor("baseline_scored_results.csv", threshold=0.70)

    # Run Gender Audit for testing the JSON output
    gender_audit = auditor.evaluate_slice("gender", "Male", "Female", None)

    print(json.dumps(gender_audit, indent=2))